spring:
  application:
    name: IMTY
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB-URL}
    password: ${DB-PASSWORD}
    username: ${DB-USERNAME}
  jpa:
    hibernate: ddl-auto:update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true